import { ImageResponse } from 'next/og';

/**
 * Dynamic OpenGraph image for christfields2717.com.
 *
 * Replaces the legacy static /assets/og-image.png from v1. Renders crisp
 * at any size because it is generated by Satori at the edge, using the
 * real Cormorant Garamond and Inter fonts loaded fresh from Google Fonts.
 *
 * Next.js auto-uses this file as the OG image for the home route. The
 * served URL is /opengraph-image and metadata.openGraph.images is
 * auto-populated. No static image reference needed.
 */
export const runtime = 'edge';
export const size = { width: 1200, height: 630 };
export const contentType = 'image/png';
export const alt = 'Christ Fields. Iron sharpens iron.';

const SPOOFED_UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36';

async function loadGoogleFont(family: string, weight: number, italic = false) {
  const familyParam = family.replace(/ /g, '+');
  const cssUrl = `https://fonts.googleapis.com/css2?family=${familyParam}:ital,wght@${italic ? 1 : 0},${weight}&display=swap`;

  const css = await fetch(cssUrl, {
    headers: { 'User-Agent': SPOOFED_UA },
  }).then((res) => res.text());

  // Pull the actual woff2 URL out of the @font-face block
  const fontUrl = css.match(/url\((https:\/\/[^)]+\.woff2?)\)/)?.[1];
  if (!fontUrl) return null;

  return await fetch(fontUrl).then((res) => res.arrayBuffer());
}

export default async function Image() {
  const [cormorant, cormorantItalic, inter] = await Promise.all([
    loadGoogleFont('Cormorant Garamond', 500),
    loadGoogleFont('Cormorant Garamond', 500, true),
    loadGoogleFont('Inter', 500),
  ]);

  return new ImageResponse(
    (
      <div
        style={{
          width: '100%',
          height: '100%',
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          position: 'relative',
          background:
            'radial-gradient(ellipse at 50% 28%, rgba(201, 165, 72, 0.14) 0%, transparent 55%), radial-gradient(ellipse at 50% 95%, rgba(45, 106, 79, 0.22) 0%, transparent 60%), #060908',
        }}
      >
        {/* Top gold accent line */}
        <div
          style={{
            position: 'absolute',
            top: 0,
            left: 0,
            right: 0,
            height: 3,
            background:
              'linear-gradient(90deg, transparent 0%, rgba(201, 165, 72, 0.85) 50%, transparent 100%)',
          }}
        />

        {/* Eyebrow */}
        <div
          style={{
            color: '#C9A548',
            fontSize: 22,
            fontFamily: 'Inter',
            fontWeight: 500,
            textTransform: 'uppercase',
            letterSpacing: 6,
            marginBottom: 36,
            display: 'flex',
          }}
        >
          Proverbs 27:17
        </div>

        {/* Wordmark */}
        <div
          style={{
            color: '#F0F2EE',
            fontFamily: 'Cormorant Garamond',
            fontSize: 132,
            fontWeight: 500,
            lineHeight: 1,
            letterSpacing: -1,
            display: 'flex',
          }}
        >
          Christ Fields
        </div>

        {/* Tagline */}
        <div
          style={{
            color: '#E4C97A',
            fontFamily: 'Cormorant Garamond',
            fontSize: 56,
            fontStyle: 'italic',
            fontWeight: 500,
            marginTop: 32,
            display: 'flex',
          }}
        >
          Iron sharpens iron.
        </div>

        {/* Bottom URL */}
        <div
          style={{
            position: 'absolute',
            bottom: 56,
            color: '#8A9A92',
            fontFamily: 'Inter',
            fontSize: 18,
            fontWeight: 500,
            textTransform: 'uppercase',
            letterSpacing: 4,
            display: 'flex',
          }}
        >
          christfields2717.com
        </div>
      </div>
    ),
    {
      ...size,
      fonts: [
        ...(cormorant
          ? [
              {
                name: 'Cormorant Garamond',
                data: cormorant,
                weight: 500 as const,
                style: 'normal' as const,
              },
            ]
          : []),
        ...(cormorantItalic
          ? [
              {
                name: 'Cormorant Garamond',
                data: cormorantItalic,
                weight: 500 as const,
                style: 'italic' as const,
              },
            ]
          : []),
        ...(inter
          ? [
              {
                name: 'Inter',
                data: inter,
                weight: 500 as const,
                style: 'normal' as const,
              },
            ]
          : []),
      ],
    },
  );
}
